name: Build and publish the project as a nuget package to github package registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish package
      run: dotnet pack --configuration Release --no-build --output ./nupkgs

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_PACKAGE_TOKEN }}